cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository  

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  REPORT_PORT: 8080
  MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
  JAVA_OPTS: -XX:MaxRAMPercentage=90
  MAVEN_OPTS: "-Dmaven.repo.local=$MAVEN_REPO_PATH"
  SAST_EXCLUDED_ANALYZERS: "eslint, nodejs-scan"

stages:
  - build
  - test
  - release
  - deploy 
  - notify  

include:
  - template: Security/SAST.gitlab-ci.yml

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend-report"
      --dockerfile "${CI_PROJECT_DIR}/backend-report/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/sausage-backend-report:$CI_COMMIT_SHA"
      --build-arg VERSION=$VERSION
      --cache=true

spotbugs-sast:
  stage: test
  needs:
    - build 
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 11
    SPRING_FLYWAY_ENABLED: "false"
  

    
release:
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: [ ]
  stage: release
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/sausage-backend-report:$CI_COMMIT_SHA $VERSION



deploy-backend-report:
  stage: deploy
  image: docker:24.0.7-alpine3.19
  before_script:
    - apk add openssh-client bash gettext
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts  
    - docker context create remote --description "remote ssh" --docker "host=ssh://${DEV_USER}@${DEV_HOST}"
  script:
    - echo "VERSION=${VERSION}" >> deploy.env
    - echo "PORT=8080" >> deploy.env
    - echo "REPORT_PATH=/var/www-data/htdocs" >> deploy.env
    - echo "REPORTS_MONGODB_URI="mongodb://${MB_USER}:${MB_PASSWORD}@${MB_HOST}:27018/${MD_BD}?tls=true"" >> deploy.env
    - cat deploy.env
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker --context remote compose --env-file deploy.env up backend-report -d --pull "always" --force-recreate 

   


      

telegram-notification-backend-report:
  stage: notify
  only:
    changes:
      - backend-report/**/*
    variables:
      - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
    - 'curl -X POST -H "Content-type: application/json" --data "{\"chat_id\": \"-1002073237519\", \"text\": \"Дмитрий собрал backend-report и провел статический анализ кода https://gitlab.praktikum-services.ru/std-ext-007-22/sausage-store/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=$CI_JOB_NAME\" }" https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage '
  needs:
    - deploy-backend-report
